language: csharp
mono: none
dotnet: 2.0.0
cache: dotnet
script:
    - dotnet restore -v q
    - dotnet build --no-restore -v q
    - dotnet test --no-build --no-restore -v q src/EasyDesignPatterns.Tests/EasyDesignPatterns.Tests.csproj
