matrix:
    include:
        - language: csharp
          mono: none
          dotnet: 2.0.0
          script:
            - ./scripts/dotnet-build.sh
            - ./scripts/dotnet-test.sh 
            
        - language: node_js
          cache:
              directories:
                - "node_modules"  
          node_js:
            - "node"
          install:
            - ./scripts/frontend-install.sh
          script:
            - ./scripts/frontend-build.sh
            - ./scripts/frontend-test.sh
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
after_success:
  - ./scripts/docker-publish-travis.sh
notifications:
  email:
    on_success: never
    on_failure: always
