jobs:
    include:
        - stage: API
        - language: csharp
          mono: none
          dotnet: 2.0.0
          before_script:
            - chmod ugo+x scripts/*
        - stage: BUILD
          script: ./scripts/dotnet-build.sh
        - stage: UNIT_TESTS
          script: ./scripts/dotnet-test.sh 
            
        - language: node_js
          cache:
              directories:
                - "node_modules"  
          node_js:
            - "node"
          before_install:
            - chmod ugo+x scripts/*
          install:
            - ./scripts/frontend-install.sh
          script:
            - ./scripts/frontend-build.sh
            - ./scripts/frontend-test.sh
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: always